// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { resolve } from "node:path";
import { defineConfig } from "prisma/config";

// Prisma CLI runs from backend/ — load .env from project root and src/.env (server uses src/.env)
config({ path: resolve(process.cwd(), ".env") });
config({ path: resolve(process.cwd(), "src/.env") });

const normalizeDatabaseUrl = (url: string | undefined): string => {
  const value = (url || "").trim();

  return value
    .replace(/^DATABASE_URL=/, "")
    .replace(/^['"]|['"]$/g, "");
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: normalizeDatabaseUrl(process.env["DATABASE_URL"]),
  },
});
